### ISSUE TITLE
Does not build on Fedora Rawhide

### ISSUE THREAD

**Issue by lzap** [kjn/lbzip2#22]
Hello there!

Upcoming changes in glibc 2.28 broke the package.

https://koji.fedoraproject.org/koji/taskinfo?taskID=28542910

https://kojipkgs.fedoraproject.org//work/tasks/2910/28542910/build.log

```
gcc -DHAVE_CONFIG_H -I.     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c -o printf-args.o printf-args.c
fseterr.c: In function 'fseterr':
fseterr.c:77:3: error: #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
  #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
   ^~~~~
make[3]: *** [Makefile:1474: fseterr.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

Thanks for help.

**Comment by hanetzer** [comment]
Same here on gentoo. Thought it was an issue for arm but also exists for amd64 systems w/gcc-8.
An update of gnulib would do the trick.

**Comment by lzap** [comment]
Thanks, please poke me once new release is wild so I can update the Fedora package. Not sure if I have release monitor on lbzip2.

**Comment by lzap** [comment]
Hello, any updates?

**Comment by logological** [comment]
For those who want a version of the source distribution that builds with glibc ≥2.28, but who lack the time or knowledge to do so themselves, I've [forked this repository](https://github.com/logological/lbzip2) and added [signed, buildable source releases for v2.5](https://github.com/logological/lbzip2/releases/tag/v2.5).

I have also updated the [OBS project for lbzip2](https://build.opensuse.org/package/show/Archiving/lbzip2) so that it uses my source release.  This means that you can now once again get working [source and binary RPMs for lbzip2 for openSUSE and SUSE Linux Enterprise Server](https://software.opensuse.org//download.html?project=Archiving&package=lbzip2).

Hopefully these will serve until @kjn is able to update the official distribution in this repository.

**Comment by 0xaf1f** [comment]
To avoid using a third party source distribution, these are the steps I had to do for updating the gnulib distribution in the tarball:

* Retrieve and extract gnulib
 ```
wget -O gnulib.tar.gz "https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=snapshot;h=HEAD;sf=tgz"
tar -xf gnulib.tar.gz
```

* enter the lbzip2 directory (assuming you downloaded it already) and get ready to update gnulib. `gnulib-tool` refuses to run until you bump up the minimum required autoconf version.
```
cd lbzip2
sed -i '/AC_PREREQ/s/2.63/2.64/' configure.ac
```

* Update gnulib. We're supposed to be able to update all the existing modules in the source directory by simply running `../gnulib/gnulib-tool --add-import` (see https://www.gnu.org/software/gnulib/manual/gnulib.html#Simple-update ), but this didn't actually work, so I had to figure out what all the used modules are through trial and error. Here you go:

```
../gnulib/gnulib-tool --import pthread-h xalloc dtotimespec gettime timespec-{add,sub} fdutimensat
```

* bootstrap and configure/build/install. The rest of the installation as usual.
```
autoreconf
./configure
make
make check
make install
```

**Comment by caius72** [comment]
This one looks closeable: the failure was in gnulib's `fseterr.c`, and the CMake build the tree uses now does not pull in gnulib at all — there is no `lib/` directory and no gnulib references under `src/`. It builds against current glibc; I have CI doing it on `ubuntu-latest` on every push, and on musl through an Alpine container.
